Implement missing speed functions along with durable speech rate / speed changer function.
idiap/coqui-ai-TTS pull request #239
Opened 2024-12-29 21:30 UTC by isikhi

As I can see coqui tts repo contuniues on this repo. So i want to add same pr into this one. Thanks! Here is the details:

Added missing speed parameters to functions and ensured more durable, accurate speed adjustments with the new `adjust_speech_rate` function.

Base Repo Ref:  https://github.com/coqui-ai/TTS/pull/4115

2024-12-29 21:37 UTC, isikhi commented
Since I learned that this repo is no longer used and maintained, I am closing the mr here and opening it to idiap's repo. It continues from here. https://github.com/idiap/coqui-ai-TTS/pull/239/

2025-01-15 13:44 UTC, eginhard requested changes
Thank you for the PR and sorry for the slow response! I would suggest a slightly different approach to support setting the `speed` for XTTS. Coqui has a bunch of different models where speed can be modified in different ways and for now I don't want to commit to a single method in `api.py`.

What will also work is to remove any reference to `speed` from `api.py`. If a `speed` argument is then specified by the user, it will then be automatically passed to models that can handle it via the `**kwargs`. Would you like to make these changes? Otherwise I can take care of it at some point.

2025-01-19 13:24 UTC, isikhi commented
@eginhard thank you for the feedback! i am not entirely familiar with all the Coqui TTS models, but I guess I understand your suggestion. But i want to clarify again. are you recommending that instead of passing speed directly, I should rely on **kwargs to handle it dynamically?

For example, would this be closer to what you have in mind?
```
wav = self.tts(  
    text=text,  
    speaker=speaker,  
    language=language,  
    speaker_wav=speaker_wav,  
    split_sentences=split_sentences,  
    **kwargs,  # `speed` would be included here if specified by the user  and check in the body of function
)  
```

i guess with this way, any user-specified speed would automatically propagate to models that support it, without hardcoding it in api.py. please let me know if this aligns with your comment or if there’s another approach you’d prefer. 

i am not advanced in python and coqui but i am happy to make further adjustments if i can do with your guidence.

2025-01-19 14:51 UTC, eginhard commented
Exactly. What's currently blocking `speed` to be passed through the `kwargs` is that some functions in `api.py` have it as an explicit argument (although it's not actually used then), so after removing those it should just work.

2025-01-20 19:29 UTC, isikhi commented
I was going to change and remove them from directly but then i realize for users whose version numbers are not strictly fixed, systems that call any function containing speed and use it in its current form might encounter issues (since there are no private accessors defined, making every function accessible). To avoid a BC (backward compatibility) break, I believe it would be more appropriate to leave speed as it is. However, if a BC break is not a concern and we are planning to release a new major version, I can proceed with the changes.

2025-01-21 11:36 UTC, eginhard commented
Well before you couldn't set `speed` and after that change you can, so that is an improvement and doesn't really break anything :)

2025-02-05 11:15 UTC, eginhard commented
@isikhi Are you still working on this? Do you need any help?

2025-02-09 11:06 UTC, isikhi commented
sorry @eginhard i cant move furthermore on that. you can take over from me

2025-02-22 10:10 UTC, UtkuBulkan commented
Along with speed argument, is there any chance that you might implement a "duration" argument, where the output is generated in the exact "duration" that is requested by the user ?

2025-02-25 14:09 UTC, closed without merging