Update tokenizer.py
idiap/coqui-ai-TTS pull request #60
Opened 2024-07-18 08:09 UTC by akshatrocky

Added proper tokenizer support for Hindi Language which would prevent crash while fine tuning Hindi language.

2024-07-18 08:26 UTC, eginhard requested changes
Thanks a lot for the PR, this is great!

It includes some changes that are not related to Hindi because there are some small differences in the code between this fork and the original repo and it looks like you started from the original one. Could you revert these unrelated changes?

2024-07-18 08:26 UTC, eginhard commented on TTS/tts/layers/xtts/tokenizer.py
> +from hangul_romanize.rule import academic
These and other changes not related to Hindi should be reverted.

2024-07-18 08:45 UTC, akshatrocky reviewed
Changes fixed, pls check.

2024-07-22 07:31 UTC, manash997 commented
Hi @akshatrocky i am getting this error, while trying to run tokenizer script from your branch:
tokenizer.py", line 806, in test_expand_numbers_multilingual
    assert out == b, f"'{out}' vs '{b}'"
AssertionError: 'Через двенадцать целых пять десятых секунды.' vs 'Через двенадцать запятая пять секунды.'

2024-07-22 07:39 UTC, akshatrocky commented
Which language are you trying to generate @manash997 ?

2024-07-22 09:25 UTC, manash997 commented
> Which language are you trying to generate @manash997 ?
> 
> (Edit) - How are you running the tokenizer script, from fine tuning XTTS?

i just tried running it as a standalone python script. The changes for Hindi, look good to me. However wanted to test the entire script once.

2024-07-25 06:46 UTC, closed without merging

2024-07-25 14:25 UTC, eginhard commented
Yes, the checks in this file are not actually run during any tests and were probably already broken for a while. Otherwise everything looks good. The author deleted their account, so I had to recreate the PR in #64.